services:
  - type: web
    name: traces-organic-certificates
    env: python
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/project/src/.pw-browsers"
    buildCommand: pip install -r requirements.txt && PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/src/.pw-browsers python -m playwright install --with-deps chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
